### ISSUE TITLE
can someone explain whats wrong in code

### ISSUE THREAD

**Issue by ApcGamer** [ApcGamer/vannilla-javascript-calculator#1]
something is wrong in my html or javascript file

**Comment by Baha-Abdelatif** [comment]
hi ! could i help you with this issue ? what is goin' wrong ?

**Comment by ApcGamer** [comment]
i'm not able to do basic mathematic operation addition multiplication . my javascript and html file both have wrong code somewhere can you look for it

**Comment by Baha-Abdelatif** [comment]
i have copy your code in my editor and run it on a local server, everything seem running right,
i am able to do basics operations like additions or multiplications without change any file

**Comment by ApcGamer** [comment]
sorry for the inconvenience i don't know why i was getting that error thank you again :)
